version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: weekly
      day: monday
      time: "13:00"
    groups:
      all-npm-dependencies:
        patterns: ["*"]  # Group all npm updates together

  - package-ecosystem: "uv"
    directory: "backend/"
    schedule:
      interval: weekly
      day: monday
      time: "13:00"
    ignore:
      - dependency-name: "h11"
        versions: [">=0.16.0"]
    groups:
      all-uv-dependencies:
        patterns: ["*"]  # Group all uv updates together
