"""add_subscription_management_tables

Revision ID: d2a379714fa8
Revises: 732388430494
Create Date: 2025-07-04 04:54:22.114279+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a379714fa8'
down_revision: Union[str, None] = '732388430494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_usd', sa.String(), nullable=False),
    sa.Column('price_eth', sa.String(), nullable=False),
    sa.Column('turns_included', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('lemon_squeezy_product_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_active'), 'subscription_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscription_plans_plan_code'), 'subscription_plans', ['plan_code'], unique=True)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('external_transaction_id', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('product_variant', sa.String(), nullable=False),
    sa.Column('turns_purchased', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processor_fee', sa.String(), nullable=True),
    sa.Column('net_amount', sa.String(), nullable=True),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_external_transaction_id'), 'payment_transactions', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_method'), 'payment_transactions', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payment_transactions_processed_at'), 'payment_transactions', ['processed_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_type'), 'payment_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('subscription_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=False),
    sa.Column('turns_affected', sa.Integer(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_created_at'), 'subscription_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_events_event_source'), 'subscription_events', ['event_source'], unique=False)
    op.create_index(op.f('ix_subscription_events_event_type'), 'subscription_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_subscription_events_external_id'), 'subscription_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_id'), 'subscription_events', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_events_processed_at'), 'subscription_events', ['processed_at'], unique=False)
    op.create_index(op.f('ix_subscription_events_subscription_status'), 'subscription_events', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_subscription_events_user_id'), 'subscription_events', ['user_id'], unique=False)
    op.create_table('turn_usage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('turn_type', sa.String(), nullable=False),
    sa.Column('usage_context', sa.String(), nullable=False),
    sa.Column('turns_before', sa.Integer(), nullable=False),
    sa.Column('turns_after', sa.Integer(), nullable=False),
    sa.Column('feature_used', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('usage_metadata', sa.JSON(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turn_usage_history_consumed_at'), 'turn_usage_history', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_turn_usage_history_id'), 'turn_usage_history', ['id'], unique=False)
    op.create_index(op.f('ix_turn_usage_history_session_id'), 'turn_usage_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_turn_usage_history_turn_type'), 'turn_usage_history', ['turn_type'], unique=False)
    op.create_index(op.f('ix_turn_usage_history_usage_context'), 'turn_usage_history', ['usage_context'], unique=False)
    op.create_index(op.f('ix_turn_usage_history_user_id'), 'turn_usage_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_usage_history_user_id'), table_name='turn_usage_history')
    op.drop_index(op.f('ix_turn_usage_history_usage_context'), table_name='turn_usage_history')
    op.drop_index(op.f('ix_turn_usage_history_turn_type'), table_name='turn_usage_history')
    op.drop_index(op.f('ix_turn_usage_history_session_id'), table_name='turn_usage_history')
    op.drop_index(op.f('ix_turn_usage_history_id'), table_name='turn_usage_history')
    op.drop_index(op.f('ix_turn_usage_history_consumed_at'), table_name='turn_usage_history')
    op.drop_table('turn_usage_history')
    op.drop_index(op.f('ix_subscription_events_user_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_subscription_status'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_processed_at'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_external_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_event_type'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_event_source'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_created_at'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_transaction_type'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_processed_at'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_method'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_external_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_subscription_plans_plan_code'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_is_active'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
