"""Add journal tables SQLite compatible

Revision ID: a40a63247210
Revises: f5907071600d
Create Date: 2025-06-29 12:24:52.977955+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40a63247210'
down_revision: Union[str, None] = 'f5907071600d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_card_meanings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('personal_meaning', sa.Text(), nullable=False),
    sa.Column('emotional_keywords', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_card_meanings_card_id'), 'user_card_meanings', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_card_meanings_id'), 'user_card_meanings', ['id'], unique=False)
    op.create_index(op.f('ix_user_card_meanings_usage_count'), 'user_card_meanings', ['usage_count'], unique=False)
    op.create_index(op.f('ix_user_card_meanings_user_id'), 'user_card_meanings', ['user_id'], unique=False)
    op.create_table('user_reading_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=False),
    sa.Column('analysis_period_start', sa.Date(), nullable=True),
    sa.Column('analysis_period_end', sa.Date(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reading_analytics_analysis_type'), 'user_reading_analytics', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_user_reading_analytics_generated_at'), 'user_reading_analytics', ['generated_at'], unique=False)
    op.create_index(op.f('ix_user_reading_analytics_id'), 'user_reading_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_user_reading_analytics_user_id'), 'user_reading_analytics', ['user_id'], unique=False)
    op.create_table('user_reading_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('reading_snapshot', sa.JSON(), nullable=False),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('mood_before', sa.Integer(), nullable=True),
    sa.Column('mood_after', sa.Integer(), nullable=True),
    sa.Column('outcome_rating', sa.Integer(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_completed', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reading_id'], ['shared_readings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reading_journal_created_at'), 'user_reading_journal', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_reading_journal_follow_up_date'), 'user_reading_journal', ['follow_up_date'], unique=False)
    op.create_index(op.f('ix_user_reading_journal_id'), 'user_reading_journal', ['id'], unique=False)
    op.create_index(op.f('ix_user_reading_journal_is_favorite'), 'user_reading_journal', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_user_reading_journal_user_id'), 'user_reading_journal', ['user_id'], unique=False)
    op.create_table('reading_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('reminder_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("reminder_type IN ('anniversary', 'follow_up', 'milestone')", name='valid_reminder_type'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['user_reading_journal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_reminders_id'), 'reading_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reading_reminders_is_sent'), 'reading_reminders', ['is_sent'], unique=False)
    op.create_index(op.f('ix_reading_reminders_reminder_date'), 'reading_reminders', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_reading_reminders_user_id'), 'reading_reminders', ['user_id'], unique=False)
    # Removed ALTER COLUMN commands as they're not compatible with SQLite
    # The users table already has the correct structure
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed ALTER COLUMN commands from downgrade as well
    op.drop_index(op.f('ix_reading_reminders_user_id'), table_name='reading_reminders')
    op.drop_index(op.f('ix_reading_reminders_reminder_date'), table_name='reading_reminders')
    op.drop_index(op.f('ix_reading_reminders_is_sent'), table_name='reading_reminders')
    op.drop_index(op.f('ix_reading_reminders_id'), table_name='reading_reminders')
    op.drop_table('reading_reminders')
    op.drop_index(op.f('ix_user_reading_journal_user_id'), table_name='user_reading_journal')
    op.drop_index(op.f('ix_user_reading_journal_is_favorite'), table_name='user_reading_journal')
    op.drop_index(op.f('ix_user_reading_journal_id'), table_name='user_reading_journal')
    op.drop_index(op.f('ix_user_reading_journal_follow_up_date'), table_name='user_reading_journal')
    op.drop_index(op.f('ix_user_reading_journal_created_at'), table_name='user_reading_journal')
    op.drop_table('user_reading_journal')
    op.drop_index(op.f('ix_user_reading_analytics_user_id'), table_name='user_reading_analytics')
    op.drop_index(op.f('ix_user_reading_analytics_id'), table_name='user_reading_analytics')
    op.drop_index(op.f('ix_user_reading_analytics_generated_at'), table_name='user_reading_analytics')
    op.drop_index(op.f('ix_user_reading_analytics_analysis_type'), table_name='user_reading_analytics')
    op.drop_table('user_reading_analytics')
    op.drop_index(op.f('ix_user_card_meanings_user_id'), table_name='user_card_meanings')
    op.drop_index(op.f('ix_user_card_meanings_usage_count'), table_name='user_card_meanings')
    op.drop_index(op.f('ix_user_card_meanings_id'), table_name='user_card_meanings')
    op.drop_index(op.f('ix_user_card_meanings_card_id'), table_name='user_card_meanings')
    op.drop_table('user_card_meanings')
    # ### end Alembic commands ###
