"""add_is_specialized_premium_field_to_user

Revision ID: 656c03a1ecc5
Revises: 1be34bbfb3ff
Create Date: 2025-06-21 05:57:19.488628+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656c03a1ecc5'
down_revision: Union[str, None] = '1be34bbfb3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with nullable=True first, then set defaults
    op.add_column('users', sa.Column('is_specialized_premium', sa.Boolean(), nullable=True))

    # Set default value for all existing users
    op.execute("UPDATE users SET is_specialized_premium = false WHERE is_specialized_premium IS NULL")

    # Note: ALTER COLUMN operations removed for SQLite compatibility
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: ALTER COLUMN operations removed for SQLite compatibility
    op.drop_column('users', 'is_specialized_premium')
    # ### end Alembic commands ###
