"""Add user_email and customer_id to checkout_sessions table

Revision ID: c8d9e3f1a4b5
Revises: ab0152669741
Create Date: 2025-07-30 09:07:52.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d9e3f1a4b5'
down_revision: Union[str, None] = 'ab0152669741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_checkout_sessions_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_sessions_customer_id'), ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkout_sessions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_checkout_sessions_user_email'))
        batch_op.drop_column('customer_id')
        batch_op.drop_column('user_email')
    # ### end Alembic commands ###