"""add_spreads_table

Revision ID: ebbff625bede
Revises: a1726ed21cef
Create Date: 2025-06-19 04:33:53.540565+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbff625bede'
down_revision: Union[str, None] = 'a1726ed21cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spreads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('num_cards', sa.Integer(), nullable=True),
    sa.Column('positions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spreads_id'), 'spreads', ['id'], unique=False)
    op.create_index(op.f('ix_spreads_name'), 'spreads', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spreads_name'), table_name='spreads')
    op.drop_index(op.f('ix_spreads_id'), table_name='spreads')
    op.drop_table('spreads')
    # ### end Alembic commands ###
