"""add is_premium field to user model

Revision ID: efa035b1f5e8
Revises: 57d151e5e294
Create Date: 2025-06-10 11:00:07.618069+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa035b1f5e8'
down_revision: Union[str, None] = '57d151e5e294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=True)

    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remaining_free_turns', sa.Integer(), nullable=True, server_default='3'))
        batch_op.add_column(sa.Column('last_ad_watch_timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(op.f('ix_users_is_premium'), ['is_premium'], unique=False)
        batch_op.create_index(op.f('ix_users_remaining_free_turns'), ['remaining_free_turns'], unique=False)
        batch_op.create_index(op.f('ix_users_last_ad_watch_timestamp'), ['last_ad_watch_timestamp'], unique=False)

        # Add check constraints
        batch_op.create_check_constraint(
            'check_remaining_free_turns_non_negative',
            'remaining_free_turns >= 0'
        )
        batch_op.create_check_constraint(
            'check_remaining_free_turns_max',
            'remaining_free_turns <= 3'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('check_remaining_free_turns_max', type_='check')
        batch_op.drop_constraint('check_remaining_free_turns_non_negative', type_='check')
        batch_op.drop_index(op.f('ix_users_last_ad_watch_timestamp'))
        batch_op.drop_index(op.f('ix_users_remaining_free_turns'))
        batch_op.drop_index(op.f('ix_users_is_premium'))
        batch_op.drop_column('last_ad_watch_timestamp')
        batch_op.drop_column('remaining_free_turns')
        batch_op.drop_column('is_premium')

    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    # ### end Alembic commands ###
