"""add deck foreign key to card

Revision ID: cc2dc4063546
Revises: a9ef7e64ef7f
Create Date: 2025-06-08 04:47:02.229428+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2dc4063546'
down_revision: Union[str, None] = 'a9ef7e64ef7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cards_deck_id', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('cards', schema=None) as batch_op:
            batch_op.drop_constraint('fk_cards_deck_id', type_='foreignkey')
    except ValueError:
        # Constraint doesn't exist, which is fine
        pass
    # ### end Alembic commands ###
