"""add shared readings table

Revision ID: 1279f73fe821
Revises: ebbff625bede
Create Date: 2025-06-19 07:38:20.090241+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1279f73fe821'
down_revision: Union[str, None] = 'ebbff625bede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('concern', sa.Text(), nullable=False),
    sa.Column('cards_data', sa.Text(), nullable=False),
    sa.Column('spread_name', sa.String(), nullable=True),
    sa.Column('deck_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_readings_created_at'), 'shared_readings', ['created_at'], unique=False)
    op.create_index(op.f('ix_shared_readings_expires_at'), 'shared_readings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shared_readings_id'), 'shared_readings', ['id'], unique=False)
    op.create_index(op.f('ix_shared_readings_is_public'), 'shared_readings', ['is_public'], unique=False)
    op.create_index(op.f('ix_shared_readings_user_id'), 'shared_readings', ['user_id'], unique=False)
    op.create_index(op.f('ix_shared_readings_uuid'), 'shared_readings', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_readings_uuid'), table_name='shared_readings')
    op.drop_index(op.f('ix_shared_readings_user_id'), table_name='shared_readings')
    op.drop_index(op.f('ix_shared_readings_is_public'), table_name='shared_readings')
    op.drop_index(op.f('ix_shared_readings_id'), table_name='shared_readings')
    op.drop_index(op.f('ix_shared_readings_expires_at'), table_name='shared_readings')
    op.drop_index(op.f('ix_shared_readings_created_at'), table_name='shared_readings')
    op.drop_table('shared_readings')
    # ### end Alembic commands ###
