"""add_ethereum_transactions_table

Revision ID: f5907071600d
Revises: 656c03a1ecc5
Create Date: 2025-06-28 13:19:58.429451+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5907071600d'
down_revision: Union[str, None] = '656c03a1ecc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ethereum_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('eth_amount', sa.String(), nullable=False),
    sa.Column('product_variant', sa.String(), nullable=False),
    sa.Column('turns_added', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ethereum_transactions_id'), 'ethereum_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_ethereum_transactions_processed_at'), 'ethereum_transactions', ['processed_at'], unique=False)
    op.create_index(op.f('ix_ethereum_transactions_status'), 'ethereum_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_ethereum_transactions_transaction_hash'), 'ethereum_transactions', ['transaction_hash'], unique=True)
    op.create_index(op.f('ix_ethereum_transactions_user_id'), 'ethereum_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_ethereum_transactions_wallet_address'), 'ethereum_transactions', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ethereum_transactions_wallet_address'), table_name='ethereum_transactions')
    op.drop_index(op.f('ix_ethereum_transactions_user_id'), table_name='ethereum_transactions')
    op.drop_index(op.f('ix_ethereum_transactions_transaction_hash'), table_name='ethereum_transactions')
    op.drop_index(op.f('ix_ethereum_transactions_status'), table_name='ethereum_transactions')
    op.drop_index(op.f('ix_ethereum_transactions_processed_at'), table_name='ethereum_transactions')
    op.drop_index(op.f('ix_ethereum_transactions_id'), table_name='ethereum_transactions')
    op.drop_table('ethereum_transactions')
    # ### end Alembic commands ###
