"""add favorite_deck to user model

Revision ID: 57d151e5e294
Revises: 2d033e0e569b
Create Date: 2025-06-08 04:58:52.671389+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d151e5e294'
down_revision: Union[str, None] = '2d033e0e569b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_deck_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_favorite_deck_id'), ['favorite_deck_id'], unique=False)
        batch_op.create_foreign_key('fk_users_favorite_deck_id', 'decks', ['favorite_deck_id'], ['id'])

    # Set default value for existing users to Rider-Waite Tarot (deck_id = 1)
    op.execute("UPDATE users SET favorite_deck_id = 1 WHERE favorite_deck_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_favorite_deck_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_favorite_deck_id'))
        batch_op.drop_column('favorite_deck_id')
    # ### end Alembic commands ###
