name: Migrate Secrets

on:
  workflow_dispatch:
    inputs:
      confirm_migration:
        description: 'Type "YES" to confirm you want to see all secrets for migration'
        required: true
        default: 'NO'
        type: string

jobs:
  echo-secrets:
    runs-on: ubuntu-latest
    if: inputs.confirm_migration == 'YES'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo All Secrets for Migration
        run: |
          echo "🔐 ========================================="
          echo "🔐 MIGRATION SECRETS EXPORT"
          echo "🔐 ========================================="
          echo ""
          echo "⚠️  WARNING: This workflow will expose all secrets!"
          echo "⚠️  Only run this when migrating to a new repository!"
          echo "⚠️  Delete this workflow after migration is complete!"
          echo ""
          echo "📋 Copy these values to your new repository secrets:"
          echo ""
          echo "================================================"
          echo "DOCKERHUB_TOKEN"
          echo "================================================"
          echo "${{ secrets.DOCKERHUB_TOKEN }}"
          echo ""
          echo "================================================"
          echo "VPS_USER"
          echo "================================================"
          echo "${{ secrets.VPS_USER }}"
          echo ""
          echo "================================================"
          echo "VPS_HOST"
          echo "================================================"
          echo "${{ secrets.VPS_HOST }}"
          echo ""
          echo "================================================"
          echo "VPS_PROJECT_DIR"
          echo "================================================"
          echo "${{ secrets.VPS_PROJECT_DIR }}"
          echo ""
          echo "================================================"
          echo "VPS_SSH_KEY"
          echo "================================================"
          echo "${{ secrets.VPS_SSH_KEY }}"
          echo ""
          echo "================================================"
          echo "SECRETS EXPORT COMPLETE"
          echo "================================================"
          echo ""
          echo "📝 Next steps:"
          echo "1. Copy all the values above"
          echo "2. Go to your new repository"
          echo "3. Go to Settings > Secrets and variables > Actions"
          echo "4. Add each secret with the exact same name"
          echo "5. Delete this workflow file from the old repository"
          echo "6. Update your new repository workflows with the new repository name"
          echo ""
          echo "🔒 Remember to keep these secrets secure!"

      - name: Create Migration Summary
        run: |
          echo "📋 Creating migration summary file..."
          cat > migration-summary.md << 'EOF'
          # Migration Summary - GitHub Secrets

          ## Secrets to Copy to New Repository

          ### 1. DOCKERHUB_TOKEN
          **Purpose**: Docker Hub authentication for building and pushing images
          **Used in**: CI workflow for building Docker images
          **Value**: Copy from the output above

          ### 2. VPS_USER
          **Purpose**: SSH username for VPS deployment
          **Used in**: Deploy workflow for SSH access
          **Value**: Copy from the output above

          ### 3. VPS_HOST
          **Purpose**: SSH hostname/IP for VPS deployment
          **Used in**: Deploy workflow for SSH connection
          **Value**: Copy from the output above

          ### 4. VPS_PROJECT_DIR
          **Purpose**: Project directory path on VPS
          **Used in**: Deploy workflow for navigation
          **Value**: Copy from the output above

          ### 5. VPS_SSH_KEY
          **Purpose**: Private SSH key for VPS access
          **Used in**: Deploy workflow for authentication
          **Value**: Copy from the output above

          ## Migration Steps

          1. **Export Secrets**: Run this workflow and copy all values
          2. **New Repository**: Create your new repository
          3. **Add Secrets**: Go to Settings > Secrets and variables > Actions
          4. **Copy Values**: Add each secret with the exact same name
          5. **Update Workflows**: Modify workflow files for new repository name
          6. **Clean Up**: Delete this workflow from old repository
          7. **Test**: Verify deployment works in new repository

          ## Important Notes

          - Keep these secrets secure and private
          - Never commit secrets to your repository
          - Update Docker image names in workflows if needed
          - Test the deployment process in the new repository
          - Consider rotating secrets after migration for security

          ## Repository Updates Needed

          - Update Docker image names in CI workflow
          - Update domain references in configuration files
          - Update GitHub repository references in documentation
          - Update deployment paths if needed
          EOF

          echo "✅ Migration summary created: migration-summary.md"

      - name: Upload Migration Summary
        uses: actions/upload-artifact@v4
        with:
          name: migration-summary
          path: migration-summary.md
          retention-days: 1

      - name: Final Warning
        run: |
          echo ""
          echo "🚨 CRITICAL SECURITY REMINDER 🚨"
          echo "=================================="
          echo ""
          echo "⚠️  This workflow has exposed all your secrets!"
          echo "⚠️  You MUST delete this workflow file immediately!"
          echo "⚠️  The secrets are now visible in the workflow logs!"
          echo ""
          echo "🔒 Security actions required:"
          echo "1. Delete this workflow file (.github/workflows/migrate-secrets.yml)"
          echo "2. Consider rotating your secrets after migration"
          echo "3. Verify no secrets are committed to your repository"
          echo ""
          echo "📧 If you need help, contact your security team!"
